# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jbraincli < Formula
  desc "AI-powered task and memory management CLI for JosephsBrain"
  homepage "https://josephsbrain.com"
  version "1.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/terzigolu/josepshbrain-go/releases/download/v1.3.2/jbraincli_1.3.2_darwin_amd64.tar.gz"
      sha256 "0f1a12a7904bb975d886bf8361aa99764c9f8a5b2e9bde2585962851edcd7d26"

      def install
        bin.install "jbraincli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/terzigolu/josepshbrain-go/releases/download/v1.3.2/jbraincli_1.3.2_darwin_arm64.tar.gz"
      sha256 "ccdbb1f1ade4100257d2f97a6e323e35bb676e3984a6a45957f1be015a9f1fe4"

      def install
        bin.install "jbraincli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/terzigolu/josepshbrain-go/releases/download/v1.3.2/jbraincli_1.3.2_linux_amd64.tar.gz"
      sha256 "5b378bec339cd49e3b210c68af822dd181701a3e5dbb025096f03d041cd55ca5"
      def install
        bin.install "jbraincli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/terzigolu/josepshbrain-go/releases/download/v1.3.2/jbraincli_1.3.2_linux_arm64.tar.gz"
      sha256 "a4b666eef12983492f105269a13fb3e115973b8dc79d6dafa8a34c1d86661567"
      def install
        bin.install "jbraincli"
      end
    end
  end

  test do
    system "#{bin}/jbraincli", "--version"
  end
end
