# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jbraincli < Formula
  desc "AI-powered task and memory management CLI for JosephsBrain"
  homepage "https://josephsbrain.com"
  version "1.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/terzigolu/josepshbrain-go/releases/download/v1.3.1/jbraincli_1.3.1_darwin_amd64.tar.gz"
      sha256 "65e6f55c9586d415638ee3931c2ed38f2fc24e547a213ce4d37a3750b598bd14"

      def install
        bin.install "jbraincli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/terzigolu/josepshbrain-go/releases/download/v1.3.1/jbraincli_1.3.1_darwin_arm64.tar.gz"
      sha256 "0f90232e1e3344d0353039ea7ae330f02658abe8e7c7c6c5eefa4356574d9637"

      def install
        bin.install "jbraincli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/terzigolu/josepshbrain-go/releases/download/v1.3.1/jbraincli_1.3.1_linux_amd64.tar.gz"
      sha256 "bbaf8d8ea557b332933f3d6e74f4e5c221efbdb9dc0b37e208b3554415e01707"
      def install
        bin.install "jbraincli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/terzigolu/josepshbrain-go/releases/download/v1.3.1/jbraincli_1.3.1_linux_arm64.tar.gz"
      sha256 "59b9cc67247c1f4d23543d84811790c152faa303a61ee8d7d615a09eb639b695"
      def install
        bin.install "jbraincli"
      end
    end
  end

  test do
    system "#{bin}/jbraincli", "--version"
  end
end
