# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jbraincli < Formula
  desc "AI-powered task and memory management CLI for JosephsBrain"
  homepage "https://josephsbrain.com"
  version "1.3.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/terzigolu/josepshbrain-go/releases/download/v1.3.3/jbraincli_1.3.3_darwin_amd64.tar.gz"
      sha256 "db59a3df570a29d306e1c226f30b26452bdc485962d975c1ab72d0774f25dd3d"

      def install
        bin.install "jbraincli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/terzigolu/josepshbrain-go/releases/download/v1.3.3/jbraincli_1.3.3_darwin_arm64.tar.gz"
      sha256 "e148a97af4ade390f0e8452c013dd9cc3f5f09d6be000e01a952b5c355655ee9"

      def install
        bin.install "jbraincli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/terzigolu/josepshbrain-go/releases/download/v1.3.3/jbraincli_1.3.3_linux_amd64.tar.gz"
      sha256 "cdda0cbece9870aebd2153cc13774b76d92926731f41a348d4b2ae1c014f90b8"
      def install
        bin.install "jbraincli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/terzigolu/josepshbrain-go/releases/download/v1.3.3/jbraincli_1.3.3_linux_arm64.tar.gz"
      sha256 "0add874659d2aed160b67e5b0ce42a7ae89775979e7654f3590bc01f6e954d78"
      def install
        bin.install "jbraincli"
      end
    end
  end

  test do
    system "#{bin}/jbraincli", "--version"
  end
end
